# Sparse Nonparametric Models Towards Accurate Forecasting: An Application to Groundwater Level Data {#sec-GW}

We plan to apply the proposed variable selection methodology and modelling framework to forecast groundwater levels using data from the Australian Groundwater Explorer[^1], which is the fourth objective of the thesis.

[^1]: <http://www.bom.gov.au/water/groundwater/explorer/>

The first step of the modelling process would be to select a suitable bore location, and to obtain series of historical head measurements of the selected bore wells. Initially, the model will be utilised to forecast the bore level of a single bore. Later, the modelling framework will be applied to forecast the bore levels of different bores (of a region) simultaneously through a proper multivariate extension.

Rainfall is one of the important predictor variables in groundwater level forecasting. Hence, another step in the modelling process is to find relevant rainfall locations. Note that this choice of rainfall locations will be crucial as the distance between the bore location and the rainfall locations will have a direct impact on the results. It will also be critical to determine other relevant predictor variables such as temperature, river/canal discharges (if relevant to the selected bore location), pumping rates, and the bore levels of neighbouring bores, etc.

Apart from the statistical models, a natural tendency towards experimenting the possible use of machine learning models in the applications of interest is observed.  The use of neural network models in groundwater level modelling was studied by @Clark2020, as a modern approach to time series regression. The authors compared the performance of classical Autoregressive Integrated Moving Average (ARIMA) models, a number of Feed-forward Neural Network (FFNN) models, and Long Short-Term Memory networks (LSTM, an updated version of Recurrent Neural Networks (RNN)), in forecasting groundwater level data taking climate data as predictors through an extensive simulation study. Moreover, the forecasting performance of ARIMA and LSTM models were further studied and compared in application to water level data obtained from a monitoring bore located in the Richmond River catchment in eastern Australia. Hence, we propose to compare the forecasting performance of the statistical model of interest (semi-parametric partially linear group-wise additive index model) to the neural network models discussed by @Clark2020.

Furthermore, it is intriguing to compare these models to the "white-box" models proposed in the hydrology literature [@Bakker2019]. In particular, we would like to obtain estimates of uncertainty in the forecasts, which is a characteristic often overlooked in this area, but of major interest in applications.
