project:
  type: book

book:
  title: "Optimal Predictor Selection for High-dimensional Nonparametric Forecasting"
  author: "Nuwani Kodikara Palihawadana"
  chapters:
    - text: "Front matter"
      file: index.qmd
    - "01-chap1.qmd"
    - "02-chap2.qmd"
    - "03-chap3.qmd"
    - "04-chap4.qmd"
    - "05-chap5.qmd"
    - "refs.qmd"
  sidebar:
    style: "docked"

bibliography: thesisrefs.bib
csl: american-statistical-association.csl
degreetype: Doctor of Philosophy
submitted: 2025
affiliation: Department of Econometrics & Business Statistics
degrees: 'B.Sc. (Hons), University of Colombo, Sri Lanka'

format:
  monashthesis-html: default
  monashthesis-pdf: default
